### ISSUE TITLE
Live search is broken with php 8.3

### ISSUE THREAD

**Issue by redsally** [WPDreams/ajax-search-pro-development#113]
The live search has suddenly stopped working on our site when server php changed from 7.4 - 8.3. 

https://www.abmprof.com.au/find-an-abm-practitioner/

The posts display correctly on page load, then as soon as any search parameter is added (via text or filter) it comes up with a "This request has failed. Please check your connection. 1" message.

I've followed all instructions I can find online, there is no cacheing on the site. Have turned off other plugins, no change in fault...

The plugin has worked perfectly since install on php 7.4.

Have tried in Safari, Firefox, Chrome, both Mobile and Desktop. 

The site is running Elementor using Hello (child) theme, minimal plugins.

**Comment by ernestmarcinko** [comment]
Hi,

The plugin is tested and developed on latest PHP versions, this might be in relation to something else as well.

Can you please share the last PHP error logs? There is no specific error reported on the page. Turning on wordpress debug mode may also help identifying the issue.

**Comment by redsally** [comment]
Thanks for your reply Ernest, it's so weird!  When I switch the site back to php 7.4 it works perfectly, when it is 8.0 or higher it throws the error.

I'll attach the error log, it does look like there has been issues for longer, though the search function was working... I'm certainly not an expert in php errors though!

thanks & cheers, Sally

[abmprof_com_au.php.error.log](https://github.com/wpdreams/ajax-search-pro-development/files/15388909/abmprof_com_au.php.error.log)

**Comment by ernestmarcinko** [comment]
Thanks, I see something interesting there.

Can you please check the options on the **General Options -> Limits** panel, to see if all of them are set and all of them are numbers, like on the picture below.

![image](https://github.com/wpdreams/ajax-search-pro-development/assets/6159897/96189318-c326-44cf-accd-8c0906ccb396)

**Comment by redsally** [comment]
Aha, that worked!  Thank you!

**Comment by ernestmarcinko** [comment]
Great!

**Comment by redsally** [comment]
Hey Ernesto, the same issue has resurfaced, no settings have been changed since the last fix.... All plugins are up to date, wordpress is up to date... the search filters just suddenly stopped working again :(

**Comment by redsally** [comment]
I can upload the current error log if needed?

**Comment by ernestmarcinko** [comment]
Yes please, that would help a lot!

**Comment by redsally** [comment]
Sorry for the delay, here it is...
[Uploading abmprof_com_au.php.error.log…]()

**Comment by ernestmarcinko** [comment]
It looks like it didn't upload before submission. Can you please try again?

**Comment by redsally** [comment]
Sorry!

[abmprof_com_au.php.error.log](https://github.com/user-attachments/files/16068149/abmprof_com_au.php.error.log)

**Comment by ernestmarcinko** [comment]
I still only see the same error, that is, there is an empty or a string value somewhere within the limits. Can you please check [all of these again](https://github.com/wpdreams/ajax-search-pro-development/issues/113#issuecomment-2123042162)? Make sure there are no empty spaces, tabs or any other characters before/after the numbers either, only the numbers and nothing else.

Non-numeric characters should be converted, but I have overlooked something I guess. It's still not your fault though, they should be corrected automatically.

**Comment by redsally** [comment]
Thanks Ernesto, there was one field which had the value removed... but I'm sure when I fixed it last time they were all filled, so that's weird! It's working again now, but is it possible to have those fields filled with default values in case of this ever happening again?  It's annoying that when it breaks the only way we can notice is by someone trying to use the search.

**Comment by ernestmarcinko** [comment]
It should be defaulted. I will review it before the next release for sure.
