### ISSUE TITLE
Error message on installing Ajax Search pro version 4.26.11 on Wordpress 6.5.3

### ISSUE THREAD

**Issue by cheikinm** [WPDreams/ajax-search-pro-development#125]
See attached screenshots.  Please advise. Thanks. cheikinm@msn.com
![ajax search pro warning v46 26 11 20240604](https://github.com/wpdreams/ajax-search-pro-development/assets/171703756/9a76061e-b58e-4f70-bb4f-0a502da79f24)
![ajax search pro warning v46 26 11 20240604](https://github.com/wpdreams/ajax-search-pro-development/assets/171703756/c9a0351e-d6ad-4392-9dde-3533831a45d1)

**Comment by ernestmarcinko** [comment]
Hi,

The screenshots does not show any error message. Can you please check again and update?

**Comment by cheikinm** [comment]
Thanks for your response. Actually a warning from Wordpress but your website says its up to date! Please advise

[cid:62ce2307-dd2a-45b9-b729-34d32a87ea93]
________________________________

**Comment by ernestmarcinko** [comment]
It's only an update message, that you should update the plugin as it is likely out of date. The website shows the changelog. Check the [update documentation](https://documentation.ajaxsearchpro.com/plugin-updates) on how to update.

**Comment by cheikinm** [comment]
I know how to update, just the first time I'm seeing this message with any plugin updates, including prior updates with Ajax Search Pro.

Thanks

________________________________

**Comment by ernestmarcinko** [comment]
All right.
