### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by edkestler** [WPDreams/ajax-search-pro-development#134]
PHP Fatal error: Uncaught TypeError: Typed property WPDRMS\ASP\Models\SearchQueryArgs::$comments_limit_override must be int, string used in /nas/content/live/techtownhq/wp-content/plugins/ajax-search-pro/includes/classes/Patterns/ObjectAsArrayTrait.php:30#012Stack trace:#012#0 /nas/content/live/techtownhq/wp-content/plugins/ajax-search-pro/includes/classes/Suggest/SuggestPostTypeTitles.php(60): WPDRMS\ASP\Models\SearchQueryArgs->__construct(Array)#012#1 /nas/content/live/techtownhq/wp-content/plugins/ajax-search-pro/includes/classes/Suggest/SuggestPostTypeTitles.php(34): WPDRMS\ASP\Suggest\SuggestPostTypeTitles->getResults(‘grill’)#012#2 /nas/content/live/techtownhq/wp-content/plugins/ajax-search-pro/includes/classes/Suggest/KeywordSuggest.php(26): WPDRMS\ASP\Suggest\SuggestPostTypeTitles->getKeywords(‘grill’)#012#3 /nas/content/live/techtownhq/wp-content/plugins/ajax-search-pro/includes/classes/Hooks/Ajax/Autocomplete.php(76): WPDRMS\ASP\Suggest\KeywordSuggest->getKeywords(‘grill’)#012#4 /nas/content/live/techtownhq/wp-includes/class-wp-hook. in /nas/content/live/techtownhq/wp-content/plugins/ajax-search-pro/includes/classes/Patterns/ObjectAsArrayTrait.php on line 30

**Comment by ernestmarcinko** [comment]
Related to #137 
Fixed.
