### ISSUE TITLE
Multisite global search stop working since 4.26.13

### ISSUE THREAD

**Issue by Krl4** [WPDreams/ajax-search-pro-development#149]
<h3 class="western"><span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;">Describe the bug</span></span></h3>
<div id=":2gq" dir="ltr">

<span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;"><span style="font-size: small;">Before version 4.26.13, the global search on multisite installations functioned as intended. You could search WooCommerce products across all sites in a WordPress multisite installation. However, since version 4.26.13 (and also in the latest version 4.26.15), the search only returns "No results". However, internal product searches within a single site of the multisite work correctly. The only change has been the plugin update.</span></span></span>
<h3 class="western"><span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;">To Reproduce</span></span></h3>
<span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;"><span style="font-size: small;">I downgraded to version 4.26.12 and it worked perfectly fine. The search bar was able to deliver products from other websites of the multisite.</span></span></span>

<span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;"><span style="font-size: small;">I installed the latest versión 4.26.15 back and the search bar only delivered the following message: "No results for xxx!"</span></span></span>
<h3 class="western"><span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;">Expected behavior</span></span></h3>
When a search bar is set up to search WooCommerce products across all sites in a WordPress multisite installation, it should return a list of products that match the search criteria, based on the websites configured in the Multisite Options section.
<h3 class="western"><span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;">Environment checklist</span></span></h3>
<ul>
 	<li><span style="color: #1f2328;"> <span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;"><span style="font-size: small;">This bug happens with a default WordPress theme active and with DIVI</span></span></span></li>
 	<li><span style="color: #1f2328;"> <span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;"><span style="font-size: small;">This bug happens with a WordPress multisite installation</span></span></span></li>
 	<li><span style="color: #1f2328;"> <span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;"><span style="font-size: small;">I can reproduce this bug consistently</span></span></span></li>
</ul>
<h3 class="western"><span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;">Desktop (please complete the following information):</span></span></h3>
<ul>
 	<li><span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;"><span style="font-size: small;">OS: linux, windows, android</span></span></span></li>
 	<li><span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;"><span style="font-size: small;">Browser chrome, brave, safari, firefox</span></span></span></li>
</ul>
<h3 class="western"><span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;">Smartphone (please complete the following information):</span></span></h3>
<ul>
 	<li><span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;"><span style="font-size: small;">Device: Samsung galaxy a25, Iphone 12</span></span></span></li>
 	<li><span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;"><span style="font-size: small;">OS: andoid, ios</span></span></span></li>
 	<li><span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;"><span style="font-size: small;">Browser brave, safari</span></span></span></li>
 	<li>&nbsp;</li>
</ul>
<h3 class="western"><span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;">Additional context</span></span></h3>
<span style="color: #1f2328;"><span style="font-family: apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;"><span style="font-size: small;">It seems that the latest version only returns results from the website where the search is initiated, regardless of the sites added in the multisite options section.</span></span></span>

</div>

**Comment by ernestmarcinko** [comment]
Thank you, this is going to be investigated next week.

**Comment by ernestmarcinko** [comment]
Finally got to this, it was identified, it was a single line of code... dang... It's going to be fixed in the next upcoming release.
