### ISSUE TITLE
Deprecated: Creation of dynamic property wpdreamsCustomPostTypes::$types is deprecated in /removed/wp-content/plugins/ajax-search-lite/backend/settings/class/customposttypes.class.php on line 64

### ISSUE THREAD

**Issue by oldrup** [WPDreams/ajax-search-pro-development#62]
Hey. Got a Pro license, and I suspect these PHP deprecation warnings will occur there as well. The following warnings are present on the lite version, however.

When testing Ajax Search with **PHP 8.2** and WP 6.4 RC2, and WP_DEBUG enabled, the Ajax Search settings panel throws several deprecation warnings. Here's a few:

![image](https://github.com/WPDreams/ajax-search-pro-development/assets/17141205/60af2d89-f0f0-48ee-a8e0-9ca585189118)

To reproduce:
- Update to PHP 8.2, enable WP_DEBUG and browse through Ajax Search's settings control panels. Most if not all does feature some deprecated PHP features/functions.

Severity:
- Low, and Ajax Search works without warnings on PHP 8.1. But eventually, we would like to upgrade.

I'd be happy to test a new beta at some point, just let me know 😊
Bjarne

**Comment by ernestmarcinko** [comment]
Hi Bjarne,

Thank you very much for the report - coincidentally this is going to be fixed within issue #25 

I will close this and reference in #25 

All the best,
Ernest

**Comment by ernestmarcinko** [comment]
For beta, can you please [fill out this form](https://ajaxsearchpro.com/development-roadmap-beta-testing/), and I will add your details to the mail contacts as well as access to the beta repo on github (which is currently empty yet).

**Comment by oldrup** [comment]
Yes! Thank you. I saw it, and will look into it next week :D Just 
released a new version of https://ressourceportal.dk/ today, featuring 
Ajax Search, so I've been busy as you can imagine. ;)

Thank you again for this fine plugin. It's really a gem.

Bjarne

On 2023-10-27 10:14, Ernest Marcinko wrote:

> PS: In the meantime I have created a beta tester team and sent you an 
> invitation in case you want to join. With that you get access to the 
> beta repository later.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/WPDreams/ajax-search-pro-development/issues/62#issuecomment-1782493234
[2]
