### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by tom-honeymoon-production** [WPDreams/ajax-search-pro-development#79]
### Describe the bug
I got the PHP error '[15-Feb-2024 16:15:26 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /wp-content/plugins/ajax-search-pro/includes/classes/Index/Tokenizer.php on line 248'

### To Reproduce
can't reproduce

### Expected behavior
avoid PHP error

### Screenshots
not available

### Environment checklist
- [ ] This bug happens with only Ajax Search Pro plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser chrome
 - Version 121.0.6167.184 (Offizieller Build) (64-Bit)
 - Plugin Version: Version 4.26.2

**Comment by ernestmarcinko** [comment]
These kinds of issues if can't be replicated are usually temporary and usually not plugin related.

The error refers to the index table tokenizer, which tries to read the contents of the post or document to index. If there is a temporary db server outage, overload it could trigger that, as the error signals that the process took too long to respond. If the document is extremely lenghty, that could also cause this, but it's very unlikely.

If the error re-occurs and is frequent, then I recommend opening a [support ticket](https://wp-dreams.com/open-support-ticket-step-1/).
