### ISSUE TITLE
translation french

### ISSUE THREAD

**Issue by domi1208** [WPDreams/ajax-search-pro-development#90]
Hello Ernest,

In response to the e-mail sent this morning, here are the screenshots to make the translations possible in French.

Regards.

Domi
![Image 001](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/581b3514-88cf-4593-8ae8-0d152402aba5)
![Image 002](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/01d6c69d-1c4e-477d-aac1-0b7228c56e0f)
![Image 003](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/f5e5ed66-9ad5-4386-bb98-5c10f4917d93)
![Image 004](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/368dcd37-197d-4736-98ea-6b8c1dbc2c54)
![Image 005](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/b1d3a1d6-947a-4ae4-a57c-a5c36d38d913)
![Image 006](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/0ac78819-907d-4206-abef-448c2891b1c2)
![Image 007](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/8cca8ce2-fe93-497a-a7ce-58cf5c15431e)
![Image 008](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/af044b74-4782-4e1a-9e76-b127289bc318)
![Image 009](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/cf38cdd7-8dd3-4388-9c3a-50ac6100dfe4)
![Image 010](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/288d44bd-939d-4bee-b292-d7b44f60fe4b)
![Image 011](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/257cd3f1-1581-4b49-9836-8036531f0e07)
![Image 012](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/60443426-bbbd-456e-b2d0-57d173aa6451)
![Image 013](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/ed4cdaf8-e891-4f84-92d7-1f6b137cb84d)

![Image 014](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/82b85121-6488-4153-8ce7-5348dfff53ea)
![Image 015](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/84c90df7-64ff-4a93-bd6a-35b5625719f7)
![Image 016](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/3676dab7-7fea-494d-8dc7-3b5ce4198af9)
![Image 017](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/47fd8291-3542-48fe-8268-a9283e9fcbb1)
![Image 018](https://github.com/WPDreams/ajax-search-pro-development/assets/163190378/73250204-0ef8-45c4-810e-e0ed1c20befa)

**Comment by ernestmarcinko** [comment]
Thank you @domi1208 I will look into these. Version 4.26.6 is under testing now, I will correct these in 4.26.7

**Comment by domi1208** [comment]
Ok Ernest, thank you. It's always a pleasure working with you!
You're reactive and serious!

domi

**Comment by ernestmarcinko** [comment]
Fixed, will be included in 4.26.7
